#!/usr/bin/perl -T
# GPLv3+ by Matija Nalis <mnalis-perl@axe.tomsoft.hr> started 2023-01-27

use warnings;
use strict;


%ENV = ( PATH => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' )
